###################################################
# BUILT-IN CONFIGURATION OPTOINS                  #
# https://gohugo.io/getting-started/configuration #
###################################################
baseURL = 'http://garden.merkleplant.xyz/'
title = "merkleplant's garden "
languageCode = 'en-us'

paginate = 5                              # number of posts each page
theme = "hugo-theme-texify"               # theme directory name

[author]
email = "me@merkleplant.xyz"
name = "merkleplant"

# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true # enable html in markdown
[markup.highlight]
style = "tango" # syntax highlight style, see https://xyproto.github.io/splash/docs/

# https://gohugo.io/content-management/menus/
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/"
weight = 1
[[menu.main]]
identifier = "wikis"
name = "Wikis"
url = "/wikis/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "https://merkleplant.xyz"
weight = 3

# https://gohugo.io/content-management/taxonomies#configure-taxonomies
[taxonomies]
series = "series" # see https://gohugo.io/templates/internal/#open-graph
tags = "tags"


########################
# TEXIFY THEME OPTIONS #
########################

[params]
description = "merkleplant's garden"
favicon = "favicon.ico"
footnote = """
Contact me on <a class=link href=https://twitter.com/merkleplant_eth>twitter</a>,
<a class=link href=https://github.com/pmerkleplant>github</a>, or via
<a class=link href="mailto:me@merkleplant.xyz">email</a> |
<a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
""" # notes in the website footer

## Use via `$$`
[params.math]
enable = true # whether to enable math typesetting
use = "katex"  # katex or mathjax

dateFormat = "2006-01-02" # date format, see https://gohugo.io/functions/format/
since = "2022"            # website created year
